/*
389. Find the Difference
https://leetcode.com/problems/find-the-difference/
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one
more letter at a random position.
Find the letter that was added in t.
Example:
Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
*/

public class Solution {
	
	// NOT mine solution, I thought to solve it by sorting arrays and comparing
    public char findTheDifference(String s, String t) {

        if(s == null || t == null)
            return Character.MIN_VALUE;

        char[] first = s.toCharArray();
        char[] second = t.toCharArray();

        int resultCode = 0;

        for(int i=0; i< first.length; i++)
            resultCode ^= (int)first[i];

        for(int i=0; i< second.length; i++)
            resultCode ^= (int)second[i];

        return (char)resultCode;
    }
}